[package]
name = "using_gtk"
version = "0.1.0"
authors = ["Eduard Vercaemer <vercaemereduard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "*"
gio = "*"
glib = "*"